################## 系统配置 ##################

search:
  includes:
    - post
    - page

################## 样式配置 ##################

# 图片配置
image:
  favicon: "/assets/favicon.png"
  avatar: "/assets/favicon.png"
  banner:
    light: "https://dev.krt.moe/demo-assets/banner.webp"
    dark: "https://dev.krt.moe/demo-assets/banner_dark.webp"
  background:
    light: "https://dev.krt.moe/demo-assets/bg.webp"
    dark: "https://dev.krt.moe/demo-assets/bg.webp"

# 顶部导航栏配置
nav:
  items:
    - label: 首页
      icon: home
      url: /
    - label: 档案馆
      icon: file
      url: /archives/
    - label: 链接
      icon: link
      submenu:
        - label: 代码仓库
          icon: code
          url: https://github.com/chen-yixin/chen-yixin.github.io
        - label: 项目文档
          icon: book
          url: https://wiki.krt.moe
    # - label: 简历
    #   icon: file-code-o
    #   url: /resume/

# Footer 页脚配置
footer:
  links:
    - icon: github
      link: https://github.com/chen-yixin
    - icon: envelope
      link: mailto:i@hoboro.top
    - icon: rss
      link: /atom.xml
  components:
    uptime:
      since: "2020-10-24 00:00:00"
      text: "本站已在风雨中飘摇"
    author:
      homepage: "https://github.com/chen-yixin/chen-yixin.github.io/graphs/contributors"
    additional: # 托管信息等
      - - 由 <a href="https://hexo.io" target="_blank" rel="nofollow">Hexo</a> 强力驱动
        - 在 <a href="https://marketing.qiniu.com/cps/redirect?redirect_id=4&cps_key=1hhtlnlchjhoy" target="_blank">七牛云</a> 和 <a href="https://github.io" target="_blank">Github Pages</a> 暖心托管
      - - 您是本站的第 <span data-path="/index.html" class="waline-pageview-count"></span> 位访客
      - - <a href="https://beian.miit.gov.cn/" target="_blank" rel="nofollow">苏ICP备2020060705号</a>

# 代码高亮
# syntax_highlighter:
#   theme: atom-dark # 代码高亮主题（请参照具体的高亮插件对应的主题样式）

# Widgets 侧边栏小挂件
sidebar:
  widgets:
    - about
    - splitter
    - toc
    - category
    - tagcloud
    - posts

# 分享组件设置
share:
  enable: true
  title: "分享这一刻"
  message: "让朋友们也来瞅瞅！"
  platforms:
    - name: "微博"
      icon: "weibo"
      color: "#e6162d"
      link: "https://service.weibo.com/share/share.php?url=$URL&title=$TITLE"
    - name: "X"
      icon: |
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-brand-x">
          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
          <path d="M4 4l11.733 16h4.267l-11.733 -16z" />
          <path d="M4 20l6.768 -6.768m2.46 -2.46l6.772 -6.772" />
        </svg>
      color: "#000"
      link: "https://x.com/intent/tweet?text=$TITLE&url=$URL"

# 打赏组件设置
donate:
  enable: true
  title: "赞助喵"
  message: 非常感谢您的喜欢！ <i class="fa fa-heart" style="color:#d43f57"></i>
  qrcode_placeholder: "https://dev.krt.moe/demo-assets/donate.webp"
  platforms:
    - name: "支付宝"
      icon: |
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-brand-alipay">
          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
          <path d="M19 3h-14a2 2 0 0 0 -2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2 -2v-14a2 2 0 0 0 -2 -2z" />
          <path d="M7 7h10" />
          <path d="M12 3v7" />
          <path d="M21 17.314c-2.971 -1.923 -15 -8.779 -15 -1.864c0 1.716 1.52 2.55 2.985 2.55c3.512 0 6.814 -5.425 6.814 -8h-6.604" />
        </svg>
      color: "#1677ff"
      qrcode: "https://qr.alipay.com/fkx12558jros7arqrmfhra0"
    - name: "微信支付"
      icon: "wechat"
      color: "#38ad5a"
      qrcode: "wxp://f2f0m3UZ64vbp2W0Ocm80zjMsDLO9GFmt3aHtyrNXOYvZzc"

# 版权说明
copyright_notice:
  in_page:
    enable_at:
      - post
      - page

# 评论系统
comments:
  core:
    enable_at:
      - index
      - post
      - page
    template:
      _shared: ""
      index: ""
      post: <div id="w-comments" class="kr-comments" data-path="$PATH"></div>
      page: <div id="w-comments" class="kr-comments" data-path="$PATH"></div>
  count:
    enable_at:
      - index
      - post
    template:
      _shared: <span data-path="$PATH" class="waline-comment-count"> </span>
      index: ""
      post: ""

# 访问数量统计
visit_count:
  enable_at:
    - index
    - post
  template:
    _shared: <span data-path="$PATH" class="waline-pageview-count"> </span>
    index: ""
    post: ""

################## 额外的注入代码 ##################
additional_injections:
  head: |
    <link rel="stylesheet" href="https://unpkg.com/@waline/client@v3/dist/waline.css" />
    <link rel="stylesheet" href="/comments/waline.css" />
  footer: ""
  after_footer: |
    <script defer type="module" src="/comments/waline.js"></script>
